services:
  - type: web
    name: e-commercedummy1
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
